<?php

return [
    [
        'id' => 1,
        'name' => '200W Solar Panel',
        'price' => 4500,
        'image' => 'https://via.placeholder.com/300x200?text=Solar+Panel',
        'category' => 'Solar Panels',
        'rating' => 4,
        'created_at' => now()->subDays(10),
    ],
    [
        'id' => 2,
        'name' => '5kVA Inverter',
        'price' => 9500,
        'image' => 'https://via.placeholder.com/300x200?text=Inverter',
        'category' => 'Inverters',
        'rating' => 5,
        'created_at' => now()->subDays(5),
    ],
    [
        'id' => 3,
        'name' => '12V 200Ah Battery',
        'price' => 7200,
        'image' => 'https://via.placeholder.com/300x200?text=Battery',
        'category' => 'Batteries',
        'rating' => 3,
        'created_at' => now()->subDays(20),
    ],
    [
        'id' => 4,
        'name' => '10kW Generator',
        'price' => 25000,
        'image' => 'https://via.placeholder.com/300x200?text=Generator',
        'category' => 'Generators',
        'rating' => 4,
        'created_at' => now()->subDays(15),
    ],
    [
        'id' => 5,
        'name' => '3HP Water Pump',
        'price' => 4200,
        'image' => 'https://via.placeholder.com/300x200?text=Water+Pump',
        'category' => 'Water Pumps',
        'rating' => 4,
        'created_at' => now()->subDays(12),
    ],
    [
        'id' => 6,
        'name' => '150W Solar Panel',
        'price' => 3800,
        'image' => 'https://via.placeholder.com/300x200?text=Solar+Panel',
        'category' => 'Solar Panels',
        'rating' => 4,
        'created_at' => now()->subDays(30),
    ],
    [
        'id' => 7,
        'name' => '1kVA Inverter',
        'price' => 4200,
        'image' => 'https://via.placeholder.com/300x200?text=Inverter',
        'category' => 'Inverters',
        'rating' => 2,
        'created_at' => now()->subDays(3),
    ],
    [
        'id' => 8,
        'name' => '24V 100Ah Battery',
        'price' => 8800,
        'image' => 'https://via.placeholder.com/300x200?text=Battery',
        'category' => 'Batteries',
        'rating' => 5,
        'created_at' => now()->subDays(8),
    ],
    [
        'id' => 9,
        'name' => '20kW Generator',
        'price' => 42000,
        'image' => 'https://via.placeholder.com/300x200?text=Generator',
        'category' => 'Generators',
        'rating' => 4,
        'created_at' => now()->subDays(1),
    ],
    [
        'id' => 10,
        'name' => '5HP Water Pump',
        'price' => 7800,
        'image' => 'https://via.placeholder.com/300x200?text=Water+Pump',
        'category' => 'Water Pumps',
        'rating' => 3,
        'created_at' => now()->subDays(18),
    ],
    [
        'id' => 11,
        'name' => '250W Solar Panel',
        'price' => 5200,
        'image' => 'https://via.placeholder.com/300x200?text=Solar+Panel',
        'category' => 'Solar Panels',
        'rating' => 5,
        'created_at' => now()->subDays(2),
    ],
    [
        'id' => 12,
        'name' => '8kVA Inverter',
        'price' => 17000,
        'image' => 'https://via.placeholder.com/300x200?text=Inverter',
        'category' => 'Inverters',
        'rating' => 4,
        'created_at' => now()->subDays(25),
    ],
    [
        'id' => 13,
        'name' => '48V 300Ah Battery',
        'price' => 16500,
        'image' => 'https://via.placeholder.com/300x200?text=Battery',
        'category' => 'Batteries',
        'rating' => 2,
        'created_at' => now()->subDays(7),
    ],
    [
        'id' => 14,
        'name' => '2kW Generator',
        'price' => 8000,
        'image' => 'https://via.placeholder.com/300x200?text=Generator',
        'category' => 'Generators',
        'rating' => 5,
        'created_at' => now()->subDays(9),
    ],
    [
        'id' => 15,
        'name' => '1HP Water Pump',
        'price' => 2400,
        'image' => 'https://via.placeholder.com/300x200?text=Water+Pump',
        'category' => 'Water Pumps',
        'rating' => 3,
        'created_at' => now()->subDays(22),
    ],
];
